---

# automate.py in OODS build_tools repo contains an up-to-date list of build deps
# https://github.com/ONLYOFFICE/build_tools/blob/master/tools/linux/automate.py
# Actually, installing these deps are not strictly necessary, as the build script
# handles their installation anyway
- name: Install build dependencies
  ansible.builtin.apt: 
    name:
      - apt-transport-https
      - autoconf2.13
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - git
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libgtk-3-dev
      - libpulse-dev
      - libtool
      - p7zip-full
      - subversion
      - gzip
      - libasound2-dev
      - libatspi2.0-dev
      - libcups2-dev
      - libdbus-1-dev
      - libicu-dev
      - libglu1-mesa-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libx11-xcb-dev
      - libxcb*
      - libxi-dev
      - libxrender-dev
      - libxss1
      - libncurses5
      # additional build deps that were listed by autoize.com blog post
      # note that autoize.com is considered outdated:
      # https://github.com/ONLYOFFICE/DocumentServer/issues/858#issuecomment-620035737
      - wget
      - libcurl4-gnutls-dev
      - libglib2.0-dev
      - libgdk-pixbuf2.0-dev
      - libgtkglext1-dev
      - libatk1.0-dev
      - libcairo2-dev
      - libxml2-dev
      - libxss-dev
      - libgconf2-dev
      - qt5-qmake
      - qt5-default
    state: present
